info:
  description: asdf3
logging:
  level:
    org.springframework.web: DEBUG
    com.nab.nlinkweb: DEBUG
application:
  logging:
    level: INFO

management.endpoints.web.exposure.include: '*'

hystrix.command.StoreSubmission.execution.isolation.thread.timeoutInMilliseconds: 5000

hystrix.timer.threadpool.default.coreSize: 30
hystrix.threadpool.default.coreSize: 5
hystrix.threadpool.default.maxQueueSize: 1000
hystrix.threadpool.default.queueSizeRejectionThreshold: 100

