info:
  description: asdf3
logging:
  level:
    org.springframework.web: DEBUG
    com.nab.nlinkweb: DEBUG
    org.springframework.ws.client.MessageTracing.sent: TRACE
    org.springframework.ws.server.MessageTracing.sent: TRACE
    org.springframework.ws.client.MessageTracing.received: TRACE
    org.springframework.ws.server.MessageTracing.received: TRACE

application:
  logging:
    level: INFO

services:
  currencyConverter:
    endpoint: http://www.webservicex.com/stockquote.asmx

management.endpoints.web.exposure.include: '*'

hystrix.command.StoreSubmission.execution.isolation.thread.timeoutInMilliseconds: 5000

hystrix.timer.threadpool.default.coreSize: 30
hystrix.threadpool.default.coreSize: 5
hystrix.threadpool.default.maxQueueSize: 1000
hystrix.threadpool.default.queueSizeRejectionThreshold: 100




