swagger: "2.0"
info:
  description: "This is nlink API"
  version: "1.0.0"
  title: "nlink"


schemes:
- "http"
paths:
  /report:
    post:
      summary: "create new report"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "required information to generate report "
        required: true
        schema:
          $ref: "#/definitions/Report"
      responses:
        405:
          description: "Invalid input"



definitions:
  Category:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
    xml:
      name: "Category"
  Report:
    type: "object"
    required:
    - "name"
    properties:
      id:
        type: "integer"
        format: "int64"
      category:
        $ref: "#/definitions/Category"
      name:
        type: "string"
        example: "doggie"

  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
